# file per ignorare il warning che occorre durante la pipeline CI per qualcosa di deprecato nella libreria transformers di Hugging Face
# aggiro il warning con questo codice
[pytest]
filterwarnings =
    ignore:Deprecated in 0.9.0. BPE.__init__ will not create from files anymore:DeprecationWarning